language: python
dist: xenial
python:
- 3.7
install:
- pip install pipenv
- pipenv install --dev
- cp .env.in .env
script:
- pipenv run pytest
after_success: 
cache:
  pip: true
notifications:
  webhooks:
    secure: GybUWuV0jjX6861LwAVhC/lJLaNxfNkhHuhN2r1KCRyaegAvk5IeyKpAZuTi5fgz0ck/tHPqelomFuaMszMi0QMIJb7sGSul9ptQ/psTvuxwuic6mfOFztN7v7wW04XQgGKJJc6AqQ+V8OHyawQk/Q9ozQxpqSlBEEwuR5EJZSiMh066aMuhl3M9JiQgduWfu59T64junbSNTKVyPyQMW52H0aI+i3guAMzMdHAEC8APcz5KFGCfoQmWXQKeMttQcNgDup08RK+IWBq/Ga2JCYlSGtdYyhQxXa7NU2Z17ohKacZnFV4sXDNp/ask/W51cvjNA9BcxJwlAGzOu6eUL+jzqNGeCDqyujX9geTGjK60pk2Bbud52hsT1wct8pTYqvDFeVPjihiA6qsSVJmUdR12cvck3fi76yEqO3gd+Koz4Egy0zk/lX2ETjOzAAfZixWnxNTk921J3Zs59OJVYwJawaOKI5Kfo6rZJ7AOJzIut7gk3op9NgGn63c9hFsorohCEXXgrzMta6n2zB0rewMPuKI1I04y13cCDL9AuRftR7vsfoe483Cnwo0QCQHdQUD/d2WoE/QswVliPulCNQhR+2N9neOzZVAj4EANRxbNQNemWV04jrBujIg+0/WGc8YeJKOzl6swBr8aE8v3efuEw0wtuC2S78M+0N+va3U=