image: python:3.7
pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install pipenv
          - pipenv install --dev
          - cp .env.in .env
          - pipenv run pytest
